default: &default
  adapter: postgresql
  encoding: unicode
  username: deploy
  password: henrique
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: authable_development

test:
  <<: *default
  database: authable_test

production:
  <<: *default
  database: authable_production
